# Generated by Django 4.1.4 on 2022-12-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_producto_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.TextField(default='caracol'),
        ),
    ]
