# Generated by Django 4.1.4 on 2022-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_producto_precio_producto_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.TextField(null=True),
        ),
    ]
